const series1: string[] = [
    "oh hello there",
    "whichever way you're going",
    "gemstones",
    "for you",
    "the wizard knows",
    "pausing to reflect",
    "excited to tell you",
    "comfort",
    "almost missed this",
    "curious object",
    "shy approach",
    "impressed, patient",
    "out for a stroll",
    "aglow",
    "best friends",
    "reflecting, remembering",
    "a secret plan",
    "on the move",
    "pause to breathe",
    "gentle giant",
    "reaching",
    "moving day",
    "oh and-- don't forget--",
    "relay race",
    "pure affection",
    "treasured knowledge",
    "wonder",
    "on my way",
    "please?",
    "protection & armor",
    "in flight",
    "uncertain, daydreaming",
    "opening up",
    "right here with you",
    "traveling companion",
    "fluidity",
    "quiet guidance",
    "casting the spell",
    "tiny crew",
    "lost in thought",
    "in the dance",
    "like no time has passed",
    "sunny day walk",
    "kind listener",
    "dancing like...",
    "zero gravity game",
    "found object",
    "confidence, determination",
    "moving forward with purpose",
    "is that so?"
]

const series2: string[] = [
    "out for a swim",
    "rehearsing what I'll say",
    "satisfied - job well done",
    "pouring energy",
    "vantage point",
    "I have an idea",
    "guard, relaxed",
    "proud ancestry",
    "sympathetic joy",
    "oh! what I meant was",
    "enthralled reading",
    "reading in the park",
    "casting my first spell",
    "fountain and treasure",
    "means of transportation",
    "learning to crawl",
    "yes, why do you ask?",
    "ribbon",
    "got to see this through",
    "gliding through",
    "pausing here a while",
    "do I recognize you...?",
    "story telling",
    "waiting patiently",
    "musical instrument",
    "distance throw",
    "well, I wasn't expecting that",
    "I am fond of this",
    "keep it glowing",
    "hearts",
    "perched",
    "meditative state",
    "dressed up",
    "drying off",
    "carrying the source",
    "rest, my friend",
    "mid-story",
    "do they know...?",
    "it's beautiful, thank you!",
    "any second now...",
    "beverage",
    "no obstacles stop me",
    "hello, small one",
    "I protect them",
    "hiding place?",
    "surfboard",
    "royal crown",
    "I've got this",
    "simple explanation",
    "what have I found?"
]

const series3: string[] = [

    "conjured embrace",
    "flickering light",
    "in the shadow of",
    "a place to rest",
    "formal occasion",
    "firecracker",
    "following your lead",
    "star",
    "what magic does it hold?",
    "undeterred",
    "ready to act",
    "amazed & seeing",
    "a bit shy",
    "ancent music",
    "skating",
    "emerging from sleep",
    "bird",
    "giving it some thought",
    "looking back",
    "depth",
    "keeping an eye on you",
    "then I found this",
    "delicate and strong",
    "enough",
    "whirling",
    "wind-blown",
    "source of water",
    "practicing the conversation",
    "new morning joy",
    "go-together motions",
    "oh! now I understand",
    "yes, that's for you",
    "what my music looks like",
    "lost in thought",
    "gliding peacefully",
    "ethereal",
    "peaceful dream",
    "uncertain dance",
    "book",
    "rest in the sun",
    "at sunset",
    "inspiration, uplifting",
    "sent & received",
    "memories, wonder",
    "sculptor daydreaming",
    "on the platform",
    "magic transportation service",
    "in this moment",
    "right?",
    "cautious, trusting"
]

const series4: string[] = [

    "something to say",
    "I trust you",
    "feeling cute",
    "adventure together",
    "listening for the melody",
    "gazing in wonder",
    "full of ideas",
    "I hadn't thought of that",
    "not for just anyone",
    "hidden bird",
    "amused!",
    "let's explore together",
    "mixing the potion",
    "naptime",
    "wait, what if...",
    "love note",
    "arriving at the dance",
    "traveling musician",
    "reverent pose",
    "peering into the deep",
    "serious look",
    "a gift",
    "favorite toy",
    "y'know, I wonder...",
    "in the shade of trees",
    "tumbling",
    "I am enough",
    "traveler with a bag",
    "still figuring this out",
    "let me tell you...",
    "stars visit",
    "leaping dancer",
    "this one's mine",
    "seeing what's in the distance",
    "look what I found",
    "to do list",
    "sparkle",
    "favorite fruit",
    "getting the giggles",
    "hop hop hop",
    "ah! a sunbeam",
    "creature flow",
    "up to something",
    "hoping",
    "trying this on",
    "gliding so easily",
    "floating above me",
    "teeth",
    "every part in motion",
    "carrying this with me"
]

const series5: string[] = [

    "magician creating",
    "summer day ",
    "creature yoga",
    "savoring the thought",
    "bird is hard to hold",
    "glow above",
    "feathers on top",
    "thinking as I walk",
    "sharing a smile",
    "practice throw",
    "serene",
    "would that work? hmm...",
    "cool relief",
    "creature love",
    "restful sleep",
    "listening carefully",
    "daydreaming",
    "majestic",
    "brought you this",
    "balanced",
    "hanging out",
    "late night walk",
    "getting ready",
    "creature rock star",
    "still in dreamland",
    "might bite",
    "how's it going",
    "dance moves",
    "cape",
    "warm space in the sun",
    "gimme some steam",
    "floating although heavy",
    "fireworks",
    "...me?",
    "friendly wave",
    "3-D art installation",
    "forewarned is...",
    "spoken to the sky",
    "bringing an important piece",
    "on my pillow",
    "I didn't realize that",
    "I'm ready",
    "hat and a dance",
    "whoa!",
    "night time running",
    "flexibility",
    "startled look",
    "even creatures check",
    "colorful cute",
    "nose"
]

const series6: string[] = [
    "whistle",
    "thinking the plan through",
    "floating in water",
    "prepared to defend",
    "rainbow walker",
    "walking in shadows",
    "check this out",
    "pendulum",
    "how I move",
    "wary, planning a game",
    "crafting in clay",
    "bringing flame",
    "majestic presence",
    "explaining how it works",
    "little flower",
    "the little one sings",
    "dreamy look",
    "found the piece I was missing",
    "magical delivery",
    "this keeps me warm",
    "whew",
    "carpet",
    "resting/flying",
    "the largest",
    "a lot going on",
    "waiting for the vision",
    "climbing on the rocks",
    "trying to remember how it was",
    "presenting...",
    "flight and light",
    "small friends",
    "anticipating what's ahead",
    "fuzzy",
    "happy",
    "awkward tools",
    "flag bearer",
    "colorful runner",
    "maybe a little?",
    "sharp",
    "considering the options",
    "silver beard",
    "ahh, satisfied",
    "try this",
    "looking up, shaded",
    "this is the one",
    "three",
    "generating energy",
    "I can fix it",
    "you know...",
    "forwards or backwards"
]

const series7: string[] = [
    ""
]

export default [series1, series2, series3, series4, series5, series6, series7]